// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyjdsmdrwhrbammeivek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5amRzbWRyd2hyYmFtbWVpdmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTc0MTksImV4cCI6MjA2NTIzMzQxOX0.posI7iBdmqfPpU88Wkduv6fVo-IgWbo2XyF1ECcFeKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);